Nambah Menu Setting
IOH-C22-HY-4/MobileDevelopment pull request #16
Opened 2022-05-18 08:17 UTC by ni-sasa

2022-05-18 08:28 UTC, Vincent-Sirait approved these changes
nicee

2022-05-18 09:07 UTC, onirutlA requested changes

2022-05-18 12:53 UTC, ni-sasa reviewed
Revisi Setting Menu

2022-05-18 22:48 UTC, onirutlA commented
Coba di build sa masih gk bisa di build ini ada errorny

2022-05-19 05:55 UTC, onirutlA approved these changes

2022-05-19 07:11 UTC, merged