Nambah Detail Profile
IOH-C22-HY-4/MobileDevelopment pull request #21
Opened 2022-05-19 15:06 UTC by ni-sasa

2022-05-19 23:08 UTC, onirutlA requested changes

2022-05-19 23:08 UTC, onirutlA commented on app/src/main/res/layout/activity_detail_profile.xml
> +        tools:ignore="ContentDescription,MissingConstraints"
Kenapa di ignore missing constraintnya

2022-05-19 23:08 UTC, onirutlA commented on app/src/main/res/layout/activity_detail_profile.xml
> +        tools:layout_editor_absoluteX="250dp"
Ini jg kenapa masih pake tools:absolute

2022-05-20 02:37 UTC, ni-sasa commented on app/src/main/res/layout/activity_detail_profile.xml
> +        tools:ignore="ContentDescription,MissingConstraints"
Oiya lupa :(

2022-05-20 02:38 UTC, ni-sasa reviewed
Done Revisi

2022-05-20 02:49 UTC, onirutlA approved these changes

2022-05-20 11:47 UTC, Vincent-Sirait approved these changes
nicee

2022-05-20 11:52 UTC, merged